FROM image-registry.openshift-image-registry.svc:5000/netbox/netbox-app

USER root

# Adapted from upgrade.sh
# manage.py needs a key, this is a bogus one!
RUN mkdocs build && \
  NETBOX_SECRET_KEY="6l0~ZBT9yFIQoZxak9H=N_f6~@Yhbu~YS4s6r8-R2%GwXZVV)0" \
  python3 netbox/manage.py collectstatic --no-input

FROM docker.io/galenguyer/nginx:1.21.3
COPY --from=0 /opt/netbox/netbox/static /usr/share/nginx/html/static
