apiVersion: batch/v1beta1
kind: CronJob
metadata:
  name: netbox-housekeeping
spec:
  schedule: "0 3 * * *"
  jobTemplate:
    spec:
      template:
        spec:
          containers:
          - name: netbox-housekeeping-run
            image: image-registry.openshift-image-registry.svc:5000/netbox/netbox-app:latest
            command:
            - python3
            - netbox/manage.py
            - housekeeping
            env:
              - name: NETBOX_REDIS_PASS
                valueFrom:
                  secretKeyRef:
                    name: redis
                    key: database-password
            imagePullPolicy: Always
            envFrom:
              - configMapRef:
                  name: netbox-secrets
              - secretRef:
                  name: netbox-secret-key
              - secretRef:
                  name: netbox-aws
              - secretRef:
                  name: netbox-db-pass
              - secretRef:
                  name: netbox-mail
              - secretRef:
                  name: netbox-ldap
          restartPolicy: OnFailure
