apiVersion: batch/v1
kind: Job
metadata:
  name: netbox-dev-migration
spec:
  ttlSecondsAfterFinished: 3600
  template:
    spec:
      containers:
      - name: netbox-dev-migration-runner
        image: image-registry.openshift-image-registry.svc:5000/netbox/netbox-app-dev:latest
        command: ["bash", "-ex", "migrate.sh"]
        env:
          - name: NETBOX_REDIS_PASS
            valueFrom:
              secretKeyRef:
                name: redis
                key: database-password
          # - name: NETBOX_DELETE_LEGACY_DATA
          #   value: "1"
        imagePullPolicy: Always
        envFrom:
          - configMapRef:
              name: netbox-dev-secrets
          - secretRef:
              name: netbox-secret-key
          - secretRef:
              name: netbox-aws
          - secretRef:
              name: netbox-db-pass
          - secretRef:
              name: netbox-mail
          - secretRef:
              name: netbox-oidc-dev
      restartPolicy: Never
  backoffLimit: 2
